openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Store
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
paths:
  /order:
    post:
      summary: Save order
      operationId: saveOrder
      tags:
        - order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        201:
          description: Created
components:
  schemas:
    OrderRequest:
      type: object
      required:
        - orderId
        - orderTime
      properties:
        id:
          type: integer
          format: int64
        orderTime:
          type: integer
          format: int64
        orderAddress:
          type: string
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        status_code:
          type: string
        code:
          type: integer
          format: int32
        message:
          type: string